---
- name: "Create Ansible Service Account"
  hosts: all
  become: true
  user:
    name: svc_ansible
    password: $6$Rb9PvVrC$Y6tKmr0kzOjCFFknAr2ZQTD3UWIIaE462E5r3LL45O8e559XbjvCu$
    groups: sudo
    state: present
- name: "Allow admin users to sudo without a password"
  hosts: all
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "svc_ansible ALL=(ALL) NOPASSWD: ALL"
    state: present